name = "LogicCircuits"
uuid = "a7847b3b-b7f1-4dd5-83c3-60e0aa0f8599"
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
CSV = "0.6"
CUDA = "1.2"
DataFrames = "0.21"
LoopVectorization = "0.8.20"
MLDatasets = "0.4, 0.5"
Reexport = "0.2"
StatsFuns = "0.9"
julia = "1.5"
