name = "LogicCircuits"
uuid = "a7847b3b-b7f1-4dd5-83c3-60e0aa0f8599"
authors = ["Guy Van den Broeck <guyvdb@cs.ucla.edu>"]
version = "0.3.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DirectedAcyclicGraphs = "1e6dae5e-d6e2-422d-9af3-452e7a3785ee"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Lerche = "d42ef402-04e6-4356-9f73-091573ea58dc"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"

[compat]
CSV = "0.7, 0.8, 0.9"
CUDA = "3"
CodecZlib = "0.7"
DataFrames = "1.1, 1.2"
DirectedAcyclicGraphs = "0.1.1"
Graphs = "1.4"
Lerche = "0.5"
LoopVectorization = "0.12"
Reexport = "1.0"
StatsFuns = "0.9"
Tables = "1"
TikzGraphs = "1.3"
julia = "1.6"
